"""add is_demo field

Revision ID: 6ac96562081c
Revises: d73f0bfef2fe
Create Date: 2026-01-08 16:31:05.033786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac96562081c'
down_revision: Union[str, Sequence[str], None] = 'd73f0bfef2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_accounts', sa.Column('is_demo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_accounts', 'is_demo')
    # ### end Alembic commands ###
