"""add passphrase field

Revision ID: d73f0bfef2fe
Revises: feb8176dbfb6
Create Date: 2026-01-07 21:01:11.240328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73f0bfef2fe'
down_revision: Union[str, Sequence[str], None] = 'feb8176dbfb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_accounts', sa.Column('api_passphrase', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_accounts', 'api_passphrase')
    # ### end Alembic commands ###
